name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para leer historial de commits

      # Semantic Versioning (uses commit messages to generate version)
      - name: Generate Semantic Version
        id: version
        uses: paulhatch/semantic-version@v4.0.3
        with:
          tag_prefix: 'v'
          major_pattern: 'major:'
          minor_pattern: 'feat:'
          format: 'v{major}.{minor}.{patch}'

      - name: Show generated version
        run: |
          echo "Version generated: ${{ steps.version.outputs.version }}"

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_REGISTRY }}/graphql-cicd:${{ steps.version.outputs.version }}
            ${{ secrets.DOCKER_HUB_REGISTRY }}/graphql-cicd:latest

      - name: Verify Image Version
        run: |
          docker run --rm ${{ secrets.DOCKER_HUB_REGISTRY }}/graphql-cicd:${{ steps.version.outputs.version }} --version || true
