name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_REGISTRY }}/graphql-cicd:0.0.1 .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_REGISTRY }}/graphql-cicd:0.0.1

      - name: Verify Docker Image
        run: |
          docker run --rm ${{ secrets.DOCKER_HUB_REGISTRY }}/graphql-cicd:0.0.1 --version
